
import React, { useState, useRef, useEffect } from 'react';
import { analyzeDocumentStatement } from '../services/geminiService';
import { Bank, Expense } from '../types';

interface PDFParserProps {
  onExpensesExtracted: (expenses: Expense[]) => void;
  userCategories: string[];
  corrections: Record<string, string>;
}

const SmartScanner: React.FC<PDFParserProps> = ({ onExpensesExtracted, userCategories, corrections }) => {
  const [bank, setBank] = useState<Bank>(Bank.BCP);
  const [month, setMonth] = useState((new Date().getMonth() + 1).toString().padStart(2, '0'));
  const [year, setYear] = useState(new Date().getFullYear().toString());
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusMessage, setStatusMessage] = useState('');
  const [selectedFile, setSelectedFile] = useState<{name: string, base64: string, type: string} | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const processFile = (file: File) => {
    const reader = new FileReader();
    reader.onload = () => {
      const base64 = (reader.result as string).split(',')[1];
      setSelectedFile({ name: file.name, base64, type: file.type });
    };
    reader.readAsDataURL(file);
  };

  const handleProcess = async () => {
    if (!selectedFile) return;
    setLoading(true);
    setProgress(10);
    setStatusMessage('Iniciando análisis de documento...');

    try {
      // Simulación de progreso para mejor feedback visual
      const statusInterval = setInterval(() => {
        setProgress(prev => {
          if (prev < 40) {
            setStatusMessage('Leyendo datos del archivo...');
            return prev + 2;
          }
          if (prev < 80) {
            setStatusMessage('IA extrayendo consumos y fechas...');
            return prev + 1;
          }
          if (prev < 95) {
            setStatusMessage('Categorizando según tus reglas de aprendizaje...');
            return prev + 0.5;
          }
          return prev;
        });
      }, 500);

      const results = await analyzeDocumentStatement(
        selectedFile.base64,
        selectedFile.type,
        bank,
        month,
        year,
        userCategories,
        corrections
      );

      clearInterval(statusInterval);
      setProgress(100);
      setStatusMessage('¡Extracción completada con éxito!');

      const fullExpenses: Expense[] = results.map(e => ({
        ...e,
        id: Math.random().toString(36).substr(2, 9),
        periodMonth: month,
        periodYear: year,
        bank,
        isAutoGenerated: true
      })) as Expense[];
      
      // Pequeño delay para que el usuario vea el 100%
      setTimeout(() => {
        onExpensesExtracted(fullExpenses);
        setSelectedFile(null);
        setLoading(false);
        setProgress(0);
        setStatusMessage('');
      }, 800);

    } catch (error) {
      console.error(error);
      setStatusMessage('Error durante el procesamiento.');
      setLoading(false);
      setProgress(0);
      alert("Hubo un problema procesando el documento. Por favor, intenta de nuevo.");
    }
  };

  return (
    <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-6">
      <div class="flex items-center gap-3">
        <div class="p-2 bg-indigo-600 rounded-xl text-white">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
        </div>
        <div>
          <h3 class="text-lg font-bold text-gray-800">Escáner Inteligente</h3>
          <p class="text-xs text-gray-500">La IA detecta gastos automáticamente</p>
        </div>
      </div>

      {!loading ? (
        <>
          <div class="grid grid-cols-3 gap-3">
            <div>
              <label class="block text-[10px] font-bold text-gray-400 uppercase mb-1">Banco</label>
              <select value={bank} onChange={(e) => setBank(e.target.value as Bank)} class="w-full rounded-xl border-gray-100 bg-gray-50 text-xs font-bold focus:ring-indigo-500">
                <option value={Bank.BCP}>BCP</option>
                <option value={Bank.IBK}>Interbank</option>
              </select>
            </div>
            <div>
              <label class="block text-[10px] font-bold text-gray-400 uppercase mb-1">Mes</label>
              <select value={month} onChange={(e) => setMonth(e.target.value)} class="w-full rounded-xl border-gray-100 bg-gray-50 text-xs font-bold focus:ring-indigo-500">
                {Array.from({length: 12}, (_, i) => (
                  <option key={i+1} value={(i+1).toString().padStart(2, '0')}>{new Date(2000, i).toLocaleString('es', { month: 'short' })}</option>
                ))}
              </select>
            </div>
            <div>
              <label class="block text-[10px] font-bold text-gray-400 uppercase mb-1">Año</label>
              <input type="number" value={year} onChange={(e) => setYear(e.target.value)} class="w-full rounded-xl border-gray-100 bg-gray-50 text-xs font-bold focus:ring-indigo-500" />
            </div>
          </div>

          <div 
            onClick={() => fileInputRef.current?.click()}
            class="border-2 border-dashed border-gray-100 rounded-2xl p-8 flex flex-col items-center justify-center cursor-pointer hover:border-indigo-200 hover:bg-indigo-50/30 transition-all group"
          >
            <input type="file" ref={fileInputRef} hidden accept="application/pdf,image/*" onChange={(e) => e.target.files?.[0] && processFile(e.target.files[0])} />
            <div class="w-10 h-10 bg-gray-50 rounded-full flex items-center justify-center mb-3 group-hover:bg-indigo-100 group-hover:text-indigo-600 transition-colors">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" /></svg>
            </div>
            <p class="text-sm font-semibold text-gray-600">{selectedFile ? selectedFile.name : 'Subir voucher o PDF'}</p>
            <p class="text-[9px] text-gray-400 mt-1 uppercase tracking-widest text-center">IA Procesará consumos usando tus preferencias</p>
          </div>

          <button
            onClick={handleProcess}
            disabled={!selectedFile}
            class={`w-full py-4 rounded-xl font-bold text-white transition-all flex items-center justify-center gap-2 ${!selectedFile ? 'bg-gray-300' : 'bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-100'}`}
          >
            Comenzar Escaneo
          </button>
        </>
      ) : (
        <div class="py-8 space-y-6 animate-in fade-in duration-500">
          <div class="flex flex-col items-center text-center space-y-4">
            <div class="relative w-24 h-24">
              <svg class="w-full h-full transform -rotate-90">
                <circle
                  cx="48"
                  cy="48"
                  r="40"
                  stroke="currentColor"
                  stroke-width="8"
                  fill="transparent"
                  class="text-gray-100"
                />
                <circle
                  cx="48"
                  cy="48"
                  r="40"
                  stroke="currentColor"
                  stroke-width="8"
                  fill="transparent"
                  stroke-dasharray={251.2}
                  stroke-dashoffset={251.2 - (251.2 * progress) / 100}
                  class="text-indigo-600 transition-all duration-500 ease-out"
                />
              </svg>
              <div class="absolute inset-0 flex items-center justify-center">
                <span class="text-lg font-bold text-indigo-600">{Math.round(progress)}%</span>
              </div>
            </div>
            
            <div class="space-y-1">
              <p class="text-sm font-bold text-gray-800">{statusMessage}</p>
              <p class="text-[10px] text-gray-400 uppercase tracking-widest animate-pulse">Procesando con Gemini AI...</p>
            </div>
          </div>

          <div class="bg-indigo-50/50 p-4 rounded-xl">
             <div class="flex items-center gap-3">
                <div class="w-2 h-2 bg-indigo-600 rounded-full animate-ping"></div>
                <p class="text-[11px] text-indigo-700 font-medium">No cierres esta ventana mientras la IA analiza tu estado de cuenta.</p>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SmartScanner;
